using UnityEngine;

/// <summary>
/// The map's terrain, imported from war3map.w3e (heights, cliff levels, ramps, water, ground tiles) and war3map.wpm
/// (what can be walked and built on). Generated by Tools > Import WC3 Terrain.
///
/// Two grids, both centred on the origin, 1 world unit = 64 Warcraft III units:
///  - corners: (cornersX x cornersZ) tile corners, 2 units apart. Index = z * cornersX + x, x/z increasing east/north.
///    World position of corner (cx, cz) = (-cellsX / 2 + 2 * cx, -cellsZ / 2 + 2 * cz).
///  - cells: (cellsX x cellsZ) 1x1 pathing cells. Cell (cx, cz) covers world x in [cx - cellsX/2, cx - cellsX/2 + 1).
/// </summary>
public class TerrainMapData : ScriptableObject
{
    public int cornersX = 97, cornersZ = 97;
    public int cellsX = 192, cellsZ = 192;

    [Tooltip("Ground tile ids in the map's order, e.g. Ndrt Glav Nrck Ngrs Nice Nsnw Nsnr")]
    public string[] groundTileIds;
    [Tooltip("Cliff tile ids, e.g. CNdi CNsn")]
    public string[] cliffTileIds;

    [Header("Per corner")]
    [Tooltip("Ground height in world units, including the cliff level offset")]
    public float[] cornerHeight;
    public byte[] cornerLayer;
    [Tooltip("Index into groundTileIds")]
    public byte[] cornerGround;
    [Tooltip("Index into cliffTileIds; 15 = none")]
    public byte[] cornerCliff;
    [Tooltip("bit 0 = ramp, 1 = blight, 2 = water, 3 = map boundary")]
    public byte[] cornerFlags;
    [Tooltip("Water surface height in world units (meaningful where the water flag is set)")]
    public float[] cornerWater;

    [Header("Per cell")]
    [Tooltip("bit 0 = not walkable, bit 1 = walkable but not buildable")]
    public byte[] cellPathing;

    [Tooltip("Same flags at the map's native 32-unit resolution (2x2 per cell): fineX x fineZ")]
    public byte[] pathingFine;
    public int fineX = 384, fineZ = 384;

    public const byte FlagRamp = 1, FlagBlight = 2, FlagWater = 4, FlagBoundary = 8;
    public const byte PathBlocked = 1, PathNoBuild = 2;

    public int CornerIndex(int cx, int cz) => cz * cornersX + cx;
    public int CellIndex(int cx, int cz) => cz * cellsX + cx;
}
